#!/bin/bash

set -x

SCRIPT=$(basename $0)
SCRIPTPATH=$(realpath "$0")
SCRIPTDIR=$(dirname "$SCRIPTPATH")

MAKEFILE="$SCRIPTDIR/Makefile"

echo "# Autogenerated file" > $MAKEFILE
echo "SHELL := /bin/bash" >> $MAKEFILE

for BT in debug release; do
cat << EOF >> $MAKEFILE
.PHONY: clean-$BT
clean-$BT:
	rm -rf $BT

.PHONY: $BT
$BT:
	if [ ! -d "$BT" ]; then \
		meson setup --buildtype $BT $BT; \
	fi 
	ninja --verbose -C $BT

.PHONY: test-$BT
test-$BT:
	BUILDDIR=$BT ./test.py -v
EOF
done
