#!/bin/bash

SCRIPT=$(basename $0)
SCRIPTPATH=$(realpath "$0")
SCRIPTDIR=$(dirname "$SCRIPTPATH")

MAKEFILE="$SCRIPTDIR/Makefile"

echo "# Autogenerated file" > $MAKEFILE
echo "SHELL := /bin/bash" >> $MAKEFILE

for BT in debug release debugoptimized; do
cat << EOF >> $MAKEFILE
.PHONY: clean-$BT
clean-$BT:
	rm -rf $BT

.PHONY: build-$BT
build-$BT:
	if [ ! -d "$BT" ]; then \\
		CC=clang meson setup --buildtype $BT $BT; \\
	fi
	ninja --verbose -C $BT

.PHONY: test-$BT
test-$BT: build-$BT
	BUILDDIR=$BT FAILFAST=\$(FAILFAST) ./test.py -v -k=\$(TEST)
EOF
done
